### ISSUE TITLE
Morning session review 

### ISSUE THREAD

**Issue by codehass** [iamchristianani/portfolio#6]
In this review : 
-  Adjust the nav bar and delete the padding.
-  Add margin to icons.
-  Edit the font size for the about paragraph.
-  Change the color text in the contact section.

**Comment by iamchristianani** [comment]
Review has been done, and all fixes has been made.

- Adjust the nav bar and delete the padding. ✔️ 
- Add margin to icons. ✔️ 
- Edit the font size for the about paragraph. ✔️ 
- Change the color text in the contact section. ✔️ 

Thanks.
